# Generated by Django 5.1.6 on 2025-03-04 09:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("balance_after_transaction", models.BigIntegerField()),
                ("transaction_description", models.TextField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")],
                        max_length=50,
                    ),
                ),
                (
                    "transaction_method",
                    models.CharField(
                        choices=[
                            ("ATM", "ATM 거래"),
                            ("TRANSFER", "계좌이체"),
                            ("AUTOMATIC_TRANSFER", "자동이체"),
                            ("CARD", "카드결제"),
                            ("INTEREST", "이자"),
                        ],
                        max_length=50,
                    ),
                ),
                ("transaction_date", models.DateTimeField()),
                (
                    "account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
