# Generated by Django 5.1.6 on 2025-03-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
